### ISSUE TITLE
We need to generate a cert for hello-openshift.cloudapps.example.com

### ISSUE THREAD

**Issue by brenton** [openshift/training#100]
The router doesn't have wildcard cert support now.  I believe this was a somewhat recent change and a side effect of allowing you to have a TLS only route without getting the default HTTP route.  Until https://github.com/openshift/origin/pull/1779 lands we'll need to generate a cert to demo TLS.

**Comment by brenton** [comment]
We can abstract out the logic from `basicauthurl.sh` to do this.

**Comment by thoraxe** [comment]
In the interests of time would it make more sense just to ditch the HTTPS example and then provide a thought exercise for "INSERT SSL CERTIFICATE DATA HERE"?

**Comment by brenton** [comment]
That's fine with me.  If I get time to create the script for inserting SSL I can do it.  If someone asks we can have them look at basicauthurl.sh to see how it can be done.  I'll remote the mention of https://hello-openshift.

**Comment by brenton** [comment]
https://github.com/openshift/training/pull/132
