### ISSUE TITLE
"Visit Your Application Again" should mention that a real app would likely use DNS instead of environment variables.

### ISSUE THREAD

**Issue by brenton** [openshift/training#104]

**Comment by brenton** [comment]
The idea here is to point to some docs on SkyDNS usage inside OpenShift.

**Comment by thoraxe** [comment]
Well, SkyDNS wouldn't have any information about ports. So unless you knew that the service was using a "standard" port, wouldn't you still need an env var?

**Comment by brenton** [comment]
I think the theory is that SRV records could be hosted by SkyDNS.  I don't really feel strongly about this "issue" though.  It was just something I thought of.  We could consider doing something more interesting with SkyDNS in beta4.  If you'd prefer to do that I could move this to a card.

**Comment by thoraxe** [comment]
I guess I don't understand what the actual issue is asking for, so go ahead and make a card for beta4, and then we can create a new "enhancement" issue based on that card.
