### ISSUE TITLE
references to "ex generate" should be removed.

### ISSUE THREAD

**Issue by brenton** [openshift/training#109]
osc new-app https://github.com/openshift/centos7-wordpress.git

**Comment by brenton** [comment]
new-app is creating a service that points to ssh for some reason when you feed it that git repo.

**Comment by thoraxe** [comment]
Because the Docker file exposes ssh and http. You could probably modify the
Docker file to not expose ssh without issue for this example.

**Comment by brenton** [comment]
This is related to https://bugzilla.redhat.com/show_bug.cgi?id=1214282#c6

**Comment by thoraxe** [comment]
The only remaining ex generate references are in the wordpress example (just checked).

Previously "ex generate" also only created a service for SSH. We then manually added a service for the HTTP content.

So we either need to:
1. remove the ssh service from the Docker file
2. stick with the "add a service later" example.

Any preferences?

**Comment by brenton** [comment]
I gues it's useful to show users the sorts of complications that can arise when using stock 3rd party Dockerfiles.  I'd prefer option 2 in that case.

**Comment by sosiouxme** [comment]
Another note: `osc new-app` (as shipped in beta3) lacks the `--name` flag. So instead of everything being `wordpress-<something>` it would all be `centos7-wordpress-<something>`.

The `--name` flag is coming to new-app with next beta. Wait for that or change the add-on file? (service selector needs to match the right name)

**Comment by sosiouxme** [comment]
https://github.com/openshift/training/pull/146 currently demonstrates moving to new-app as-is.

**Comment by thoraxe** [comment]
OK, #146 looks like it fixes this issue, so I'm closing it. `grep "ex generate" beta-3-setup.md` produced no output.
