### ISSUE TITLE
Discuss need for DNS

### ISSUE THREAD

**Issue by sosiouxme** [openshift/training#12]
Despite stating that you need to set up DNS entries, there will be those for whom this is (or seems) about as easy as flapping their wings and flying to the moon. For those folks, who will nevertheless try to work around using `/etc/hosts`, I would suggest a discussion of what breaks if you _don't_ have DNS entries for the hosts and wildcard domain, so they can make an informed decision and not just ignore the directions and get stuck.

I _think_ you can actually work around the need in most cases, though I need to go through and find out for sure. The most evident immediate problem is that containers don't see the host's `/etc/hosts` so they won't be able to resolve any FQDNs, so they need to be configured with IPs.

**Comment by thoraxe** [comment]
basically nothing "breaks", but you will have to create an /etc/hosts entry for any routes that we define.

I guess there are two ways to look at this:

1) we could ditch the DNS "requirement" and simply have people do everything with /etc/hosts and show them how to examine where the router is and correctly update /etc/hosts as routes are created

2) We could include an appendix with a really simple dnsmasq setup that they could install on the master. The huge caveat with this is that if the user is not physically located on the master, they would need to update the resolver on their own machine (eg: laptop) to query dnsmasq on the master, and they would need a forwarder in dnsmasq pointing to their corp DNS or google (8.8.8.8) or etc.

(1) is probably easier, but (2) is probably more thorough and closer to real-world...

Do we know what the plan is for OSE3 to update DNS entries or incorporate skydns or anything?

**Comment by sosiouxme** [comment]
Pods can't resolve host FQDNs without DNS as they don't have /etc/hosts. So for example, the router can't resolve the master and can't get its routes.

Not quite sure what you're asking; I don't believe there's a need for DDNS in OSE v3; with the wildcard pointed at your router nothing needs to change. Setting up host DNS is a one-time admin responsibility, that much can be tough during demos but isn't the kind of thing that needs special approval the way DDNS has been. Don't know of any complicated plans for external DNS - however @smarterclayton has talked about internal DNS, skydns might be a factor there?

**Comment by thoraxe** [comment]
Well, I don't think you can really say "no requirement" for DDNS. For example, what restrictions will be in place regarding routing? Will the same concept of "namespaces" exist? What about adding custom domain routes?

In the training we currently say "point *.cloudapps.example.com at your router", but that's only because the training manually uses that domain. Nothing prevents someone from creating a route "foo.bar.baz" and pointing it at a service.

Without DDNS, if someone didn't already point foo.bar.baz at the router, it would never work.

So, depending on the user stories around routes, we may or may not need DDNS.

That being said, the pod information is valid, which means we do need some kind of real DNS. I'll look into dnsmasq.

**Comment by sosiouxme** [comment]
DNS for foo.bar.baz is outside the purview of OpenShift. Nobody actually wants OpenShift updating their DNS if they can avoid. So, as with aliases in v2, it's their responsibility to point outside URLs to the router (e.g. CNAME router.cloudapps.example.com).

The CLOUD_DOMAIN in v2 was absolutely necessary because as soon as you created the app you wanted to turn around and git clone from it. Creating an app with no DNS entry would have been an unacceptable user experience. Technically, in v3, we don't need a cloud domain at all. But we'll probably have one for convenience (so you can easily visit the app you just made), mediated by the wildcard DNS entry pointing at the router(s), and will have to figure out restrictions on what users can claim (at a minimum, keeping two services from attempting to be routed by the same name).

**Comment by thoraxe** [comment]
OK well, I am gonna look into a simple dnsmasq config to run on the master and add it as an appendix for users who need it.

**Comment by thoraxe** [comment]
Latest commit includes dnsmasq configuration.
