### ISSUE TITLE
We need an appendix on how to get the Windows and OS X client tool.

### ISSUE THREAD

**Issue by brenton** [openshift/training#123]

**Comment by brenton** [comment]
Currently staged here:
https://access.stage.redhat.com/downloads/content/289/ver=/rhel---7/0.4.3.2/x86_64/product-downloads

**Comment by thoraxe** [comment]
You mean the packages are staged there... but there's no appendix?

**Comment by sdodson** [comment]
Fixed by #139

**Comment by sdodson** [comment]
Fixed by #153
