### ISSUE TITLE
Add appendix for installing non-Linux clients

### ISSUE THREAD

**Issue by brenton** [openshift/training#145]

**Comment by sdodson** [comment]
I've updated rpm packaging to also create linux client, if we don't get this merged into origin today I'll go ahead and merge it into ose ahead of origin and have RCM include it in UD.

https://github.com/openshift/origin/pull/1974

**Comment by thoraxe** [comment]
Is this actually related to the training material, though?

**Comment by brenton** [comment]
I was thinking we'll have an appendix for how to get all the clients.

**Comment by thoraxe** [comment]
I changed the subject of the issue.

**Comment by sdodson** [comment]
Fixed by #153
