### ISSUE TITLE
Hooks section needs review

### ISSUE THREAD

**Issue by thoraxe** [openshift/training#148]
@ironcladlou can you please review the updated hooks section?

https://github.com/openshift/training/blob/master/beta-3-setup.md#lifecycle-pre-and-post-deployment-hooks

**Comment by ironcladlou** [comment]
> This has the benefit of making your entire application environment available during the hook script's execution, should you need it. 

This will be true after https://github.com/openshift/origin/issues/2005 is resolved.

**Comment by thoraxe** [comment]
Good catch.

https://github.com/openshift/training/blame/master/beta-3-setup.md#L2620 needs update.

Is it good otherwise?

**Comment by ironcladlou** [comment]
See also: https://github.com/openshift/origin/pull/2013

**Comment by ironcladlou** [comment]
Then you should be able to take out all the redundant env stuff from the hook examples.

**Comment by thoraxe** [comment]
But no changes to the description are required, right?

**Comment by ironcladlou** [comment]
Agree, looks good.
