### ISSUE TITLE
identify non-essential headings

### ISSUE THREAD

**Issue by thoraxe** [openshift/training#158]
Issue #156 discussed there was a lot of "fluff" in the TOC. This has to do with doctoc and the use of markdown headings.

My suggestion would be to only generate TOC to 2 levels deep.

Here's the resulting TOC if we do that:

```
- [OpenShift Beta 3](#openshift-beta-3)
  - [Architecture and Requirements](#architecture-and-requirements)
  - [Setting Up the Environment](#setting-up-the-environment)
  - [Ansible-based Installer](#ansible-based-installer)
  - [Watching Logs](#watching-logs)
  - [Auth, Projects, and the Web Console](#auth-projects-and-the-web-console)
  - [Your First Application](#your-first-application)
  - [Adding Nodes](#adding-nodes)
  - [Regions and Zones](#regions-and-zones)
  - [Services](#services)
  - [Routing](#routing)
  - [The Complete Pod-Service-Route](#the-complete-pod-service-route)
  - [Project Administration](#project-administration)
  - [Preparing for STI: the Registry](#preparing-for-sti-the-registry)
  - [STI - What Is It?](#sti---what-is-it)
  - [A Fully-Integrated "Quickstart" Application](#a-fully-integrated-quickstart-application)
  - [Creating and Wiring Disparate Components](#creating-and-wiring-disparate-components)
  - [Rollback/Activate and Code Lifecycle](#rollbackactivate-and-code-lifecycle)
- [ Welcome to an OpenShift v3 Demo App! ](#welcome-to-an-openshift-v3-demo-app)
- [ This is my crustom demo! ](#this-is-my-crustom-demo)
  - [Customized Build and Run Processes](#customized-build-and-run-processes)
  - [Lifecycle Pre and Post Deployment Hooks](#lifecycle-pre-and-post-deployment-hooks)
  - [Arbitrary Docker Image (Builder)](#arbitrary-docker-image-builder)
  - [Conclusion](#conclusion)
- [APPENDIX - Installing in IaaS clouds](#appendix---installing-in-iaas-clouds)
  - [Generic cloud install](#generic-cloud-install)
```

It looks like there are some formatting issues causing missing appendices and etc, but would everyone agree this is a "better" TOC?

Otherwise we are looking at:

```
- [OpenShift Beta 3](#openshift-beta-3)
  - [Architecture and Requirements](#architecture-and-requirements)
    - [Architecture](#architecture)
    - [Requirements](#requirements)
  - [Setting Up the Environment](#setting-up-the-environment)
    - [Use a Terminal Window Manager](#use-a-terminal-window-manager)
    - [DNS](#dns)
    - [Assumptions](#assumptions)
    - [Git](#git)
    - [Your Environment](#your-environment)
    - [Preparing Each VM](#preparing-each-vm)
    - [Grab Docker Images (Optional, Recommended)](#grab-docker-images-optional-recommended)
    - [Clone the Training Repository](#clone-the-training-repository)
    - [REMINDER](#reminder)
  - [Ansible-based Installer](#ansible-based-installer)
    - [Install Ansible](#install-ansible)
    - [Generate SSH Keys](#generate-ssh-keys)
    - [Distribute SSH Keys](#distribute-ssh-keys)
    - [Clone the Ansible Repository](#clone-the-ansible-repository)
    - [Configure Ansible](#configure-ansible)
    - [Modify Hosts](#modify-hosts)
    - [Run the Ansible Installer](#run-the-ansible-installer)
    - [Add Development Users](#add-development-users)
  - [Watching Logs](#watching-logs)
  - [Auth, Projects, and the Web Console](#auth-projects-and-the-web-console)
    - [Configuring htpasswd Authentication](#configuring-htpasswd-authentication)
    - [A Project for Everything](#a-project-for-everything)
    - [Web Console](#web-console)
  - [Your First Application](#your-first-application)
    - ["Resources"](#resources)
    - [Applying Quota to Projects](#applying-quota-to-projects)
    - [Login](#login)
    - [Grab the Training Repo Again](#grab-the-training-repo-again)
    - [The Hello World Definition JSON](#the-hello-world-definition-json)
    - [Run the Pod](#run-the-pod)
    - [Looking at the Pod in the Web Console](#looking-at-the-pod-in-the-web-console)
    - [Quota Usage](#quota-usage)
    - [Extra Credit](#extra-credit)
    - [Delete the Pod](#delete-the-pod)
    - [Quota Enforcement](#quota-enforcement)
  - [Adding Nodes](#adding-nodes)
    - [Modifying the Ansible Configuration](#modifying-the-ansible-configuration)
  - [Regions and Zones](#regions-and-zones)
    - [Scheduler and Defaults](#scheduler-and-defaults)
    - [The NodeSelector](#the-nodeselector)
    - [Customizing the Scheduler Configuration](#customizing-the-scheduler-configuration)
    - [Restart the Master](#restart-the-master)
    - [Label Your Nodes](#label-your-nodes)
  - [Services](#services)
  - [Routing](#routing)
    - [Creating the Router](#creating-the-router)
    - [Router Placement By Region](#router-placement-by-region)
  - [The Complete Pod-Service-Route](#the-complete-pod-service-route)
    - [Creating the Definition](#creating-the-definition)
    - [Status Report, Captain!](#status-report-captain)
    - [Verifying the Service](#verifying-the-service)
    - [Verifying the Routing](#verifying-the-routing)
    - [The Web Console](#the-web-console)
  - [Project Administration](#project-administration)
    - [Deleting a Project](#deleting-a-project)
  - [Preparing for STI: the Registry](#preparing-for-sti-the-registry)
    - [Registry Placement By Region (optional)](#registry-placement-by-region-optional)
  - [STI - What Is It?](#sti---what-is-it)
    - [Create a New Project](#create-a-new-project)
    - [Switch Projects](#switch-projects)
    - [A Simple Code Example](#a-simple-code-example)
    - [CLI versus Console](#cli-versus-console)
    - [Adding the Builder ImageStreams](#adding-the-builder-imagestreams)
    - [Wait, What's an ImageStream?](#wait-whats-an-imagestream)
    - [Adding Code Via the Web Console](#adding-code-via-the-web-console)
    - [The Web Console Revisited](#the-web-console-revisited)
    - [Examining the Build](#examining-the-build)
    - [Testing the Application](#testing-the-application)
    - [Adding a Route to Our Application](#adding-a-route-to-our-application)
    - [Implications of Quota Enforcement on Scaling](#implications-of-quota-enforcement-on-scaling)
  - [A Fully-Integrated "Quickstart" Application](#a-fully-integrated-quickstart-application)
    - [A Project for the Quickstart](#a-project-for-the-quickstart)
    - [A Quick Aside on Templates](#a-quick-aside-on-templates)
    - [Adding the Template](#adding-the-template)
    - [Create an Instance of the Template](#create-an-instance-of-the-template)
    - [The Template is Alive!](#the-template-is-alive)
    - [Using Your App](#using-your-app)
  - [Creating and Wiring Disparate Components](#creating-and-wiring-disparate-components)
    - [Create a New Project](#create-a-new-project-1)
    - [Stand Up the Frontend](#stand-up-the-frontend)
    - [Visit Your Application](#visit-your-application)
    - [Create the Database Config](#create-the-database-config)
    - [Visit Your Application Again](#visit-your-application-again)
    - [Replication Controllers](#replication-controllers)
    - [Revisit the Webpage](#revisit-the-webpage)
  - [Rollback/Activate and Code Lifecycle](#rollbackactivate-and-code-lifecycle)
    - [Fork the Repository](#fork-the-repository)
    - [Update the BuildConfig](#update-the-buildconfig)
    - [Change the Code](#change-the-code)
- [ Welcome to an OpenShift v3 Demo App! ](#welcome-to-an-openshift-v3-demo-app)
- [ This is my crustom demo! ](#this-is-my-crustom-demo)
    - [Start a Build with a Webhook](#start-a-build-with-a-webhook)
    - [Oops!](#oops)
    - [Rollback](#rollback)
    - [Activate](#activate)
  - [Customized Build and Run Processes](#customized-build-and-run-processes)
    - [Add a Script](#add-a-script)
    - [Kick Off a Build](#kick-off-a-build)
    - [Watch the Build Logs](#watch-the-build-logs)
    - [Did You See It?](#did-you-see-it)
  - [Lifecycle Pre and Post Deployment Hooks](#lifecycle-pre-and-post-deployment-hooks)
    - [A Rails Database Migration](#a-rails-database-migration)
    - [Examining the Deployment Configuration](#examining-the-deployment-configuration)
    - [Modifying the Hooks](#modifying-the-hooks)
    - [Quickly Clean Up](#quickly-clean-up)
    - [Build Again](#build-again)
    - [Verify the Migration](#verify-the-migration)
  - [Arbitrary Docker Image (Builder)](#arbitrary-docker-image-builder)
    - [That Project Thing](#that-project-thing)
    - [Build Wordpress](#build-wordpress)
    - [Test Your Application](#test-your-application)
    - [Application Resource Labels](#application-resource-labels)
  - [Conclusion](#conclusion)
- [APPENDIX - Installing in IaaS clouds](#appendix---installing-in-iaas-clouds)
  - [Generic cloud install](#generic-cloud-install)
    - [An example hosts file (/etc/ansible/hosts)](#an-example-hosts-file-etcansiblehosts)
    - [Testing the auto-detected values](#testing-the-auto-detected-values)
```

This isn't terrible, but it is a little chatty.

Thoughts?

@sdodson 
@sosiouxme

**Comment by thoraxe** [comment]
Updated section headings. Now we have:

**Doctoc Level 2**
- [OpenShift Beta 3](#openshift-beta-3)
  - [Architecture and Requirements](#architecture-and-requirements)
  - [Setting Up the Environment](#setting-up-the-environment)
  - [Ansible-based Installer](#ansible-based-installer)
  - [Useful OpenShift Logs](#useful-openshift-logs)
  - [Auth, Projects, and the Web Console](#auth-projects-and-the-web-console)
  - [Your First Application](#your-first-application)
  - [Adding Nodes](#adding-nodes)
  - [Regions and Zones](#regions-and-zones)
  - [Services](#services)
  - [Routing](#routing)
  - [The Complete Pod-Service-Route](#the-complete-pod-service-route)
  - [Project Administration](#project-administration)
  - [Preparing for STI: the Registry](#preparing-for-sti-the-registry)
  - [STI - What Is It?](#sti---what-is-it)
  - [Templates, Instant Apps, and "Quickstarts"](#templates-instant-apps-and-quickstarts)
  - [Creating and Wiring Disparate Components](#creating-and-wiring-disparate-components)
  - [Rollback/Activate and Code Lifecycle](#rollbackactivate-and-code-lifecycle)
  - [Customized Build and Run Processes](#customized-build-and-run-processes)
  - [Lifecycle Pre and Post Deployment Hooks](#lifecycle-pre-and-post-deployment-hooks)
  - [Arbitrary Docker Image (Builder)](#arbitrary-docker-image-builder)
  - [Conclusion](#conclusion)
- [APPENDIX - Extra STI code examples](#appendix---extra-sti-code-examples)
  - [Wildfly](#wildfly)
- [APPENDIX - DNSMasq setup](#appendix---dnsmasq-setup)
- [APPENDIX - LDAP Authentication](#appendix---ldap-authentication)
- [APPENDIX - Import/Export of Docker Images (Disconnected Use)](#appendix---importexport-of-docker-images-disconnected-use)
- [APPENDIX - Cleaning Up](#appendix---cleaning-up)
- [APPENDIX - Pretty Output](#appendix---pretty-output)
- [APPENDIX - Troubleshooting](#appendix---troubleshooting)
- [APPENDIX - Infrastructure Log Aggregation](#appendix---infrastructure-log-aggregation)
  - [Enable Remote Logging on Master](#enable-remote-logging-on-master)
  - [Enable logging to /var/log/openshift](#enable-logging-to-varlogopenshift)
  - [Configure nodes to send openshift logs to your master](#configure-nodes-to-send-openshift-logs-to-your-master)
  - [Optionally Log Each Node to a unique directory](#optionally-log-each-node-to-a-unique-directory)
- [APPENDIX - JBoss Tools for Eclipse](#appendix---jboss-tools-for-eclipse)
  - [Installation](#installation)
  - [Connecting to the Server](#connecting-to-the-server)
- [APPENDIX - Working with HTTP Proxies](#appendix---working-with-http-proxies)
  - [STI Builds](#sti-builds)
  - [Setting Environment Variables in Pods](#setting-environment-variables-in-pods)
  - [Git Repository Access](#git-repository-access)
  - [Proxying Docker Pull](#proxying-docker-pull)
  - [Future Considerations](#future-considerations)
- [APPENDIX - Installing in IaaS Clouds](#appendix---installing-in-iaas-clouds)
  - [Generic Cloud Install](#generic-cloud-install)
  - [Automated AWS Install With Ansible](#automated-aws-install-with-ansible)

**Doctoc Level 3**
- [OpenShift Beta 3](#openshift-beta-3)
  - [Architecture and Requirements](#architecture-and-requirements)
    - [Architecture](#architecture)
    - [Requirements](#requirements)
  - [Setting Up the Environment](#setting-up-the-environment)
    - [Use a Terminal Window Manager](#use-a-terminal-window-manager)
    - [DNS](#dns)
    - [Assumptions](#assumptions)
    - [Git](#git)
    - [Preparing Each VM](#preparing-each-vm)
    - [Grab Docker Images (Optional, Recommended)](#grab-docker-images-optional-recommended)
    - [Clone the Training Repository](#clone-the-training-repository)
  - [Ansible-based Installer](#ansible-based-installer)
    - [Install Ansible](#install-ansible)
    - [Generate SSH Keys](#generate-ssh-keys)
    - [Distribute SSH Keys](#distribute-ssh-keys)
    - [Clone the Ansible Repository](#clone-the-ansible-repository)
    - [Configure Ansible](#configure-ansible)
    - [Modify Hosts](#modify-hosts)
    - [Run the Ansible Installer](#run-the-ansible-installer)
    - [Add Development Users](#add-development-users)
  - [Useful OpenShift Logs](#useful-openshift-logs)
  - [Auth, Projects, and the Web Console](#auth-projects-and-the-web-console)
    - [Configuring htpasswd Authentication](#configuring-htpasswd-authentication)
    - [A Project for Everything](#a-project-for-everything)
    - [Web Console](#web-console)
  - [Your First Application](#your-first-application)
    - ["Resources"](#resources)
    - [Applying Quota to Projects](#applying-quota-to-projects)
    - [Login](#login)
    - [Grab the Training Repo Again](#grab-the-training-repo-again)
    - [The Hello World Definition JSON](#the-hello-world-definition-json)
    - [Run the Pod](#run-the-pod)
    - [Looking at the Pod in the Web Console](#looking-at-the-pod-in-the-web-console)
    - [Quota Usage](#quota-usage)
    - [Extra Credit](#extra-credit)
    - [Delete the Pod](#delete-the-pod)
    - [Quota Enforcement](#quota-enforcement)
  - [Adding Nodes](#adding-nodes)
    - [Modifying the Ansible Configuration](#modifying-the-ansible-configuration)
  - [Regions and Zones](#regions-and-zones)
    - [Scheduler and Defaults](#scheduler-and-defaults)
    - [The NodeSelector](#the-nodeselector)
    - [Customizing the Scheduler Configuration](#customizing-the-scheduler-configuration)
    - [Restart the Master](#restart-the-master)
    - [Label Your Nodes](#label-your-nodes)
  - [Services](#services)
  - [Routing](#routing)
    - [Creating the Router](#creating-the-router)
    - [Router Placement By Region](#router-placement-by-region)
  - [The Complete Pod-Service-Route](#the-complete-pod-service-route)
    - [Creating the Definition](#creating-the-definition)
    - [Project Status](#project-status)
    - [Verifying the Service](#verifying-the-service)
    - [Verifying the Routing](#verifying-the-routing)
    - [The Web Console](#the-web-console)
  - [Project Administration](#project-administration)
    - [Deleting a Project](#deleting-a-project)
  - [Preparing for STI: the Registry](#preparing-for-sti-the-registry)
    - [Registry Placement By Region (optional)](#registry-placement-by-region-optional)
  - [STI - What Is It?](#sti---what-is-it)
    - [Create a New Project](#create-a-new-project)
    - [Switch Projects](#switch-projects)
    - [A Simple Code Example](#a-simple-code-example)
    - [CLI versus Console](#cli-versus-console)
    - [Adding the Builder ImageStreams](#adding-the-builder-imagestreams)
    - [Wait, What's an ImageStream?](#wait-whats-an-imagestream)
    - [Adding Code Via the Web Console](#adding-code-via-the-web-console)
    - [The Web Console Revisited](#the-web-console-revisited)
    - [Examining the Build](#examining-the-build)
    - [Testing the Application](#testing-the-application)
    - [Adding a Route to Our Application](#adding-a-route-to-our-application)
    - [Implications of Quota Enforcement on Scaling](#implications-of-quota-enforcement-on-scaling)
  - [Templates, Instant Apps, and "Quickstarts"](#templates-instant-apps-and-quickstarts)
    - [A Project for the Quickstart](#a-project-for-the-quickstart)
    - [A Quick Aside on Templates](#a-quick-aside-on-templates)
    - [Adding the Template](#adding-the-template)
    - [Create an Instance of the Template](#create-an-instance-of-the-template)
    - [Using Your App](#using-your-app)
  - [Creating and Wiring Disparate Components](#creating-and-wiring-disparate-components)
    - [Create a New Project](#create-a-new-project-1)
    - [Stand Up the Frontend](#stand-up-the-frontend)
    - [Visit Your Application](#visit-your-application)
    - [Create the Database Config](#create-the-database-config)
    - [Visit Your Application Again](#visit-your-application-again)
    - [Replication Controllers](#replication-controllers)
    - [Revisit the Webpage](#revisit-the-webpage)
  - [Rollback/Activate and Code Lifecycle](#rollbackactivate-and-code-lifecycle)
    - [Fork the Repository](#fork-the-repository)
    - [Update the BuildConfig](#update-the-buildconfig)
    - [Change the Code](#change-the-code)
- [ Welcome to an OpenShift v3 Demo App! ](#welcome-to-an-openshift-v3-demo-app)
- [ This is my crustom demo! ](#this-is-my-crustom-demo)
  - [Start a Build with a Webhook](#start-a-build-with-a-webhook)
  - [Rollback](#rollback)
  - [Activate](#activate)
  - [Customized Build and Run Processes](#customized-build-and-run-processes)
    - [Add a Script](#add-a-script)
    - [Kick Off a Build](#kick-off-a-build)
    - [Watch the Build Logs](#watch-the-build-logs)
  - [Lifecycle Pre and Post Deployment Hooks](#lifecycle-pre-and-post-deployment-hooks)
    - [Examining the Deployment Configuration](#examining-the-deployment-configuration)
    - [Modifying the Hooks](#modifying-the-hooks)
    - [Quickly Clean Up](#quickly-clean-up)
    - [Build Again](#build-again)
    - [Verify the Migration](#verify-the-migration)
  - [Arbitrary Docker Image (Builder)](#arbitrary-docker-image-builder)
    - [Create a Project](#create-a-project)
    - [Build Wordpress](#build-wordpress)
    - [Test Your Application](#test-your-application)
    - [Application Resource Labels](#application-resource-labels)
  - [Conclusion](#conclusion)
- [APPENDIX - Extra STI code examples](#appendix---extra-sti-code-examples)
  - [Wildfly](#wildfly)
- [APPENDIX - DNSMasq setup](#appendix---dnsmasq-setup)
  - [Verifying DNSMasq](#verifying-dnsmasq)
- [APPENDIX - LDAP Authentication](#appendix---ldap-authentication)
  - [Prerequirements:](#prerequirements)
  - [Setting up an example LDAP server:](#setting-up-an-example-ldap-server)
  - [Creating the Basic Auth service](#creating-the-basic-auth-service)
  - [Using an LDAP server external to OpenShift](#using-an-ldap-server-external-to-openshift)
  - [Upcoming changes](#upcoming-changes)
- [APPENDIX - Import/Export of Docker Images (Disconnected Use)](#appendix---importexport-of-docker-images-disconnected-use)
- [APPENDIX - Cleaning Up](#appendix---cleaning-up)
- [APPENDIX - Pretty Output](#appendix---pretty-output)
- [APPENDIX - Troubleshooting](#appendix---troubleshooting)
- [APPENDIX - Infrastructure Log Aggregation](#appendix---infrastructure-log-aggregation)
  - [Enable Remote Logging on Master](#enable-remote-logging-on-master)
  - [Enable logging to /var/log/openshift](#enable-logging-to-varlogopenshift)
  - [Configure nodes to send openshift logs to your master](#configure-nodes-to-send-openshift-logs-to-your-master)
  - [Optionally Log Each Node to a unique directory](#optionally-log-each-node-to-a-unique-directory)
- [APPENDIX - JBoss Tools for Eclipse](#appendix---jboss-tools-for-eclipse)
  - [Installation](#installation)
  - [Connecting to the Server](#connecting-to-the-server)
- [APPENDIX - Working with HTTP Proxies](#appendix---working-with-http-proxies)
  - [STI Builds](#sti-builds)
  - [Setting Environment Variables in Pods](#setting-environment-variables-in-pods)
  - [Git Repository Access](#git-repository-access)
  - [Proxying Docker Pull](#proxying-docker-pull)
  - [Future Considerations](#future-considerations)
- [APPENDIX - Installing in IaaS Clouds](#appendix---installing-in-iaas-clouds)
  - [Generic Cloud Install](#generic-cloud-install)
    - [An Example Hosts File (/etc/ansible/hosts)](#an-example-hosts-file-etcansiblehosts)
    - [Testing the Auto-detected Values](#testing-the-auto-detected-values)
  - [Automated AWS Install With Ansible](#automated-aws-install-with-ansible)
    - [Requirements:](#requirements)
    - [Assumptions Made:](#assumptions-made)
    - [Setup (Modifying the Values Appropriately):](#setup-modifying-the-values-appropriately)
    - [Configuring the Hosts:](#configuring-the-hosts)
    - [Accessing the Hosts:](#accessing-the-hosts)

I still prefer a depth of 3.

**Comment by sosiouxme** [comment]
I prefer a depth of 3 as well. Otherwise you miss a lot of stuff I think people will definitely look for, e.g.
- [Start a Build with a Webhook](#start-a-build-with-a-webhook)
- [Rollback](#rollback)
- [Activate](#activate)

I liked the suggestion of just making the "fluff" identified in https://github.com/openshift/training/pull/156 into bold/larger text, so they still serve as a pause/section but they don't show up in the TOC. I could work up a PR for that if you want.

**Comment by thoraxe** [comment]
I think I cleaned up the fluff already with #159 

If you find any more, let me know. I'll close this issue for now.
