### ISSUE TITLE
Incorrect reference to rsyslog service

### ISSUE THREAD

**Issue by pcsherid** [openshift/training#182]
The section 'APPENDIX - Infrastructure Log Aggregation' instructs the user to restart rsyslogd with 'systemctl restart rsyslogd' which results in the following error:

Failed to issue method call: Unit rsyslogd.service failed to load: No such file or directory.

The restart command should instead be 'systemctl restart rsyslog.service' or 'systemctl restart rsyslog'.

**Comment by sdodson** [comment]
Thanks for letting us know, should be fixed now.
