### ISSUE TITLE
be sure to explicitly suggest domain changes in all locations

### ISSUE THREAD

**Issue by thoraxe** [openshift/training#186]

**Comment by thoraxe** [comment]
eg: adding sinatra route.

**Comment by thoraxe** [comment]
eg: integrated template

**Comment by thoraxe** [comment]
eg: create instance of a template (you'll see integrated...)

**Comment by thoraxe** [comment]
eg: wordpress json

**Comment by pcsherid** [comment]
In the LDAP Authentication Appendix, should the OpenLDAP source be updated if a different domain is used?

**Comment by thoraxe** [comment]
Not really. If you want to you could do that, but the fact that the OpenLDAP example uses "example.com" inside the LDAP currently isn't really referenced anywhere externally.

We're just ultimately looking at "joe" or "alice" on the LDAP side.
