### ISSUE TITLE
add partitioning suggestions to requirements

### ISSUE THREAD

**Issue by thoraxe** [openshift/training#189]

**Comment by sdodson** [comment]
We need to do some testing here, my experience has been that disk space only becomes an issue when you have looping failed containers. I'd use the following as a starting point
- / - 10G -- OS + Logs, /var/log/messages grows quick as we're chatty with docker
- /var/lib/docker - 5G --  this is where any docker auto created volumes are placed, mysql image will chew up 100M each time it's started
- /var/lib/openshift - 5G -- etcd and k8s volumes, perhaps place k8s volumes elsewhere?
- 10G+ volume group for docker storage
