### ISSUE TITLE
Default token lifetime

### ISSUE THREAD

**Issue by nak3** [openshift/training#190]
Sorry if I misunderstand, but is this statement **"the default token lifetime to 4 hours"** true?

```
Note: See the troubleshooting guide for details on how to fetch a new token once this one expires. The installer sets the default token lifetime to 4 hours.
```

Although I checked source code especially [master_args.go](https://github.com/openshift/origin/blob/6773f17b61257b2ad9176b0fd3b08a4521793921/pkg/cmd/server/start/master_args.go), I could not find where the default token lifetime sets as 4 hours.

**Comment by thoraxe** [comment]
I would think this is part of the login process. Maybe someone else can verify, but I'm pretty sure that's the case. I'm not sure who could verify, though.

**Comment by detiber** [comment]
According to the generated configs, the default token lifetimes are as follows:
authorizeTokenMaxAgeSeconds: 300 (5 minutes)
accessTokenMaxAgeSeconds: 86400 (24 hours)

What this _should_ mean is that token based auth should be valid for 24 hours, and after that 24 hours a re-auth would be necessary.  There is also refresh tokens specified in the oauth2 spec, but I am not sure if we are making use of those in the code, which would allow for access tokens to be refreshed, though with the authorizeTokenMaxAgeSeconds, I would assume that even with a refresh token auth would still be needed.

**Comment by nak3** [comment]
Thank you @thoraxe and @detiber

I believe the token lifetime is not working correctly at this moment. However, since there seems to be some commits to the upstream, I will wait to open the report until drop4.

Honestly speaking, the error message is also crazy. It should be implemented to say simply `Token expired, please login again` or something.

**Comment by thoraxe** [comment]
I think that depends on what kube tells you. Remember that the cli talks to an api which returns a status code for your request. You would probably need to open an issue upstream to request a better message. 

"Unauthorized" means just that. Whatever info you gave me isn't sufficient to authorize you. There's potentially security concerns around telling the requestor too specific information. But that's all dependent on how kubernetes responds to an api request that's token based.

**Comment by nak3** [comment]
OK, now I reported it https://github.com/openshift/origin/issues/2314
