### ISSUE TITLE
Bad MySQL volume path

### ISSUE THREAD

**Issue by mnagy** [openshift/training#195]
The openshift/mysql-55-centos7 image uses `/var/lib/mysql/data` as a volume, see https://github.com/openshift/mysql/blob/master/5.5/Dockerfile. I can see we use `/var/lib/mysql` on some places, e.g.:
https://github.com/openshift/training/blob/master/beta2/integrated-build.json#L222

This could cause some issues in the future.

**Comment by sdodson** [comment]
We've gotten away from using k8s volumes all together in the beta3 examples as they appeared to be re-used by subsequent pods and selinux was prohibiting writes. Do you know the correct volume syntax to ensure a new volume is allocated for each pod?

https://github.com/openshift/training/blob/master/beta3/integrated-template.json

**Comment by mnagy** [comment]
Not off the top of my head. If selinux was causing troubles, doesn't that mean there's a bug somewhere? If you do not specify volumes, the database will store its data inside of the container, which means they will not be persistent. Does that make sense?

**Comment by thoraxe** [comment]
Are you actually seeing any errors?

**Comment by mnagy** [comment]
@thoraxe no. But at least the json files I pointed to were wrong with the volume mounting and might cause errors or unwanted behavior later.

**Comment by sdodson** [comment]
I'm closing this as the beta3 and beta4 examples don't include any of the problematic volume mounts. The training materials thus far are cumulative so the content in beta2 and beta1 should no longer be used.
