### ISSUE TITLE
hello-openshift image needs to be referred to by version

### ISSUE THREAD

**Issue by thoraxe** [openshift/training#198]
something broke in the latest versions of the hello-openshift image and it no longer works with beta3.

the various JSON needs to be updated to explicitly specify the version number.

**Comment by thoraxe** [comment]
Brenton if you can do this or maybe @sdodson  or someone, I won't have time before next week.

**Comment by detiber** [comment]
https://github.com/openshift/training/pull/199 fixes this for the beta3 doc
