### ISSUE TITLE
ansible installer using old bootstrap policy file

### ISSUE THREAD

**Issue by ekuric** [openshift/training#200]
policy file https://gist.github.com/ekuric/f2177e28c5bc8aba034a  @sdodson  @deads2k

**Comment by deads2k** [comment]
If a policy file already exists, we should not delete it, but I wanted to be sure that the ansible installer always generates a fresh `policy.json` file when it lays it down.  We don't want to end up with an old file laid down by default.

**Comment by sdodson** [comment]
This is a beta4'ish environment? I don't have that file on my recent install. Be sure you're using the v3-beta4 branch from https://github.com/detiber/openshift-ansible

**Comment by sdodson** [comment]
Actually, ansible doesn't directly create that and we don't support upgrades so you need to wipe the environment when moving between beta3 and beta4 codebases. Easiest to reprovision the hosts, but you can also follow these steps to clean the environment https://github.com/openshift/training/blob/master/uninstall.md

**Comment by ekuric** [comment]
@sdodson beta3 and then upgraded to packages from beta4. testing now v3-beta4 branch - clean install

**Comment by sdodson** [comment]
Yeah, we don't do anything to ensure upgrades between beta releaess (and interim builds) work properly. We always assume that someone does a clean install.

Re-open if the problem happens on a clean install.
