### ISSUE TITLE
We have to use 'openshift kube' to set node labels

### ISSUE THREAD

**Issue by brenton** [openshift/training#209]
`osc edit nodes` and `osc update node -f ~/nodes.json` doesn't work because of how the kubelet updates the node records.  This can work:

```
openshift kube label node ose3-master.example.com zone=NA --overwrite
openshift kube label node ose3-node1.example.com zone=east --overwrite
openshift kube label node ose3-node2.example.com zone=west --overwrite
```

We'll need the final work from Clayton if we intend to expose that command.

**Comment by detiber** [comment]
openshift-ansible can create the node labels on creation, they just need to be specified in the inventory vars for the node.

**Comment by sosiouxme** [comment]
nodes create themselves now, but probably not with intended labels. So will need adjusting.

I _think_ `openshift kube` is intended to stay in the product at least for now.

**Comment by detiber** [comment]
@sosiouxme @brenton I discussed this with Clayton the other day, there will be something upstream to manage this (most likely to set once on node registration).  Until then we should use `osc label` instead of `openshift kube label`

**Comment by thoraxe** [comment]
I have been using "osc label" in the latest beta4 work.
