### ISSUE TITLE
Unable to add more nodes

### ISSUE THREAD

**Issue by rjleaf** [openshift/training#218]
**Version**
OpenShift Enterprise v3 Beta 3

**Platform**
RHEL 7.1 x64

**Issue**
When trying to follow the "Add More Nodes" instructions, the process fails on "msg: cannot change to directory '/var/lib/openshift/openshift.local.certificates/node-': path does not exist."

See the link below for a pastebin:
https://paste.fedoraproject.org/226611/33886143/

**Comment by thoraxe** [comment]
@rjleaf when you initially created the master/node only, did everything work OK?

`node-` looks like some kind of weird typo, though.

What's in your `/etc/ansible/hosts`?

Were you following the rest of the beta3 docs "exactly" leading up to this step?

**Comment by rjleaf** [comment]
@thoraxe Yes, when I created the master/node config, everything seemed to work fine.

One difference from the docs is that I do not have DNS set up through an external provider or through dnsmasq; I've been adding the machines manually into the master's /etc/hosts file. (Here: http://paste.fedoraproject.org/226780/68131143/) [Note: I fixed the typo and re-ran the test, no difference.]

My Ansible Hosts is here: http://paste.fedoraproject.org/226781/28681661/

**Comment by sdodson** [comment]
@rjleaf While I don't think it would cause the problem you're having right now, having your nodes in /etc/hosts is not sufficient for OpenShift to work properly. Pods must be able to resolv at least the master via the nameservers configured in /etc/resolv.conf

**Comment by craigmunro** [comment]
I had this problem.  Downgrading Ansible from 1.9.1 to 1.8.4 fixed it for me.

**Comment by rjleaf** [comment]
@craigmunro: Thanks for your suggestion. @thoraxe @detiber I tried downgrading Ansible, but it still gives me issues with the certificates. It appears that  the playbook fails to appropriately handle (not sure what it's doing exactly) certificates for each of the nodes.

**Comment by detiber** [comment]
Looking at the output of the pastebin I see this:

```
"openshift": {"common": {"deployment_type": "enterprise", "hostname": "", "ip": "192.168.155.147", "public_hostname": "", "public_ip": "192.168.155.147", "use_openshift_sdn": true}, "current_config": {"roles": ["node"]}, "node": {"annotations": {}, "external_id": "", "labels": {}, "pod_cidr": "", "resources_cpu": 2, "resources_memory": 1436024832}}}
```

What this is telling me is that the hostname and public_hostname values aren't being defined (most likely due to the missing dns entries).

The easiest workaround would be to set openshift_hostname=<pre-configured hostname> and openshift_public_hostname=<pre-configured-hostname> for each of the hosts.   Also, each of the hosts would need to be able to communicate with the other cluster hosts using their hostname.

That would at least get you to the point where you would hit the issue that @sdodson mentioned.

**Comment by detiber** [comment]
@craigmunro @rjleaf Ansible 1.8.4 should be sufficient for beta3, but beta4 brings in some ansible changes that will require ansible 1.9.1+

**Comment by rjleaf** [comment]
@detiber Thanks! Having a working dnsmasq config fixes this problem. I also came across the issue of not having a clear way to change the firewall settings to allow 53/tcp for DNS; I had to disable the firewall entirely on my node. Maybe something in the docs should reflect this?
