### ISSUE TITLE
A few minor issues with the beta4 training

### ISSUE THREAD

**Issue by tiwillia** [openshift/training#223]
- The link to extra htpasswd info is wrong. Should be:
  http://docs.openshift.org/latest/admin_guide/configuring_authentication.html#HTPasswdPasswordIdentityProvider
- "The login process created a file called .config" is wrong, actually
  creates a file called 'config'
- The hello-pod.json output is incorrect
- The hello-pod does not work, throws 'No such file or directory' when attempting to start. This is a known issue iirc.
- The link http://docs.openshift.org/latest/dev_guide/scheduler.html
  also 404's | should be
  http://docs.openshift.org/latest/admin_guide/scheduler.html

**Comment by akostadinov** [comment]
One more issue is that references to `osc` should change to `oc`. I guess acronym of `OverClock`.
Also `oadm` instead of `os-admin`. 
`osc` looks much cooler though and easier to search by search engines.

**Comment by nak3** [comment]
The command name should be changed after GA release. Beta4 still uses `osc`.

**Comment by sdodson** [comment]
@akostadinov lengthy discussion regarding renaming the commands at https://github.com/openshift/origin/pull/1007

**Comment by akostadinov** [comment]
thank you for the reference, makes sense
