### ISSUE TITLE
HA routers

### ISSUE THREAD

**Issue by sosiouxme** [openshift/training#231]
https://github.com/openshift/training/blob/beta4/beta-4-setup.md#router-placement-by-region

`For a true HA implementation, one would want multiple "infra" nodes and multiple, clustered router instances. Look for this to be described in beta4.`

Actually going to do anything with this? We could have the router run on all the nodes. We could set up multiple routers, each with a different wildcard. _shrug_ I'm not sure there's much point, can just leave it to the docs.

**Comment by sosiouxme** [comment]
Oh, I remember, we wanted the keepalived vIP.

Well, if we did that, would we want it against all the nodes or what? Specify two instances and no region restriction?

**Comment by thoraxe** [comment]
I think we will at the end just show/demonstrate how the keepalived stuff works just on the single infra node.
