### ISSUE TITLE
[beta4] sinatra-route has no endpoints

### ISSUE THREAD

**Issue by sdodson** [openshift/training#247]
I can't seem to get sinatra-route to work, everytime it has no endpoints assigned, all the other examples up through the template example in beta4 work fine.

**Comment by brenton** [comment]
It's working for me.  I installed everything with the latest binaries from cdn and registry.access.

```
#192.168.133.2 is my Master where the router pod is running in the infra region
$ curl -H "Host: hello-sinatra.cloudapps.example.com" http://192.168.133.2
Hello, Sinatra!

$ osc describe service ruby-example
Name:                   ruby-example
Labels:                 generatedby=OpenShiftWebConsole,name=ruby-example
Selector:               deploymentconfig=ruby-example
Type:                   ClusterIP
IP:                     172.30.43.166
Port:                   <unnamed>       8080/tcp
Endpoints:              <unnamed>       10.1.1.3:8080
Session Affinity:       None
No events.
```

**Comment by brenton** [comment]
My vote is for someone else to test this today and if it works close this for now.

**Comment by brenton** [comment]
I'm closing this for now.  @thoraxe saw the same behavior as me.  He opened https://github.com/openshift/origin/issues/2941 to see if the route was even supposed to have endpoints listed.
