### ISSUE TITLE
deleting db pod with persistent data breaks frontend

### ISSUE THREAD

**Issue by thoraxe** [openshift/training#256]
I noticed that after killing the DB, the db comes right back, but then the frontend app isn't working anymore.

I am wondering if this has something to do with a "persistent" socket connection to the mysql service where the back-end pod went away and was replaced but the frontend hasn't tried to "reconnect"?

I dunno what the default timeout for Ruby is on trying to reconnect?

Killing the frontend definitely makes this work, but that's likely not the desired behavior...

**Comment by brenton** [comment]
The ruby sample app is pretty dumb.  It only tries to connect on startup.

**Comment by sosiouxme** [comment]
So, short term fix, document that you need to restart the front end too.
Long term, fix the app, because it's not very cloud-y. Surprised there even exists a default behavior that doesn't detect the connection is gone and reconnect.

**Comment by thoraxe** [comment]
@brenton is it possible to fix the app to make it try to reconnect, or is this just a ruby problem? Perhaps we should do a better example (eg: nginx)?

**Comment by brenton** [comment]
It's definitely possible to fix.  Someone just needs to make time to do it.

**Comment by thoraxe** [comment]
I'm working on a PHP example...

**Comment by thoraxe** [comment]
While this isn't "fixed", #284 changes the persistent volume example to use PHP which isn't sensitive to this kind of stuff.
