### ISSUE TITLE
Regions section claimes inaccurate nodes considered

### ISSUE THREAD

**Issue by JayKayy** [openshift/training#292]
So, if we have the following nodes and the following labels:

```
Node 1 -- "region":"infra"
Node 2 -- "region":"primary"
Node 3 -- "region":"primary"
```

If we try to schedule a pod that has a NodeSelector of "region":"primary", then only Node 1 and Node 2 would be considered.

---

This last sentence should say Node 2 and Node 3 will be considered instead of 1 & 2, based on the setup given

**Comment by thoraxe** [comment]
Fixed in GA branch.
