### ISSUE TITLE
move "installing ansible" section to an appendix

### ISSUE THREAD

**Issue by cgwalters** [openshift/training#296]
We're only using EPEL to get ansible as a _client_ - which isn't entirely clear.  I think we should encourage people to run ansible from another machine (e.g. if using RHEL Workstation, you could install it there, or another RHEL server).

So "How to install and run Ansible" would be a separate section.  This would impact some other things though, such as how to copy over the example quota/pod etc. definitions.  But explaining that better would be more useful anyways.

**Comment by thoraxe** [comment]
This is actually gone completely, as we discuss only the quick installer and refer people to the official docs for other installation methods.
