### ISSUE TITLE
updates for GA docker images and instructions missing

### ISSUE THREAD

**Issue by skoussou** [openshift/training#297]
I see on GA of the training there is only still beta-4 training material. but with

subscription-manager repos --disable="*"
subscription-manager repos \
--enable="rhel-7-server-rpms" \
--enable="rhel-7-server-extras-rpms" \
--enable="rhel-7-server-optional-rpms" \
--enable="rhel-server-7-ose-beta-rpms"

when retrieving any image I receive 

[root@ose3-master ~]# docker pull registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.5.2.2
FATA[0018] Error response from daemon: v1 ping attempt failed with error: Get https://registry.access.redhat.com/v1/_ping: dial tcp: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry.access.redhat.com` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry.access.redhat.com/ca.crt 

if I follow the GA docs and still try to download the ie.
# subscription-manager repos --disable="*"
# subscription-manager repos \

--enable="rhel-7-server-rpms" \
--enable="rhel-7-server-extras-rpms" \
--enable="rhel-7-server-optional-rpms" \
--enable="rhel-7-server-ose-3.0-rpms"

then I get 
[root@ose3-master ~]# docker pull registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.5.2.2
Trying to pull repository registry.access.redhat.com/openshift3_beta/ose-haproxy-router ... not found
FATA[0010] Error: image openshift3_beta/ose-haproxy-router:v0.5.2.2 not found

**Comment by nak3** [comment]
I guess there are no `openshift3_beta` and tag `v0.5.2.2` any more.

```
[root@ose3-master ~]# docker pull registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.5.2.2
```

You can refer GA version here, although I think it is still WIP.

https://github.com/thoraxe/training/blob/GA-work/01-Requirements-and-Preparation.md

**Comment by thoraxe** [comment]
I think this is updated.
