### ISSUE TITLE
dnsmasq appendix link doesn't seem to do anything when clicked

### ISSUE THREAD

**Issue by maxamillion** [openshift/training#303]
I clicked on the link https://github.com/openshift/training/blob/GA/01-Requirements-and-Preparation.md#appendix---dnsmasq-setup and it doesn't do anything in Firefox or Chrome.

**Comment by maxamillion** [comment]
nevermind, for whatever reason this is working now.

**Comment by thoraxe** [comment]
@maxamillion the link is not "working" -- it still doesn't exist. It's a stale link until the rest of the chapters are re-written and appendices are broken out separately.

It's just not sending you to nothing / not clicking :)

**Comment by maxamillion** [comment]
I just realized that it works on the master branch in the beta4 dir and I had that open in a different tab.

**Comment by thoraxe** [comment]
:)
