### ISSUE TITLE
Referring to an non-existing chapter

### ISSUE THREAD

**Issue by PatrickSteiner** [openshift/training#321]
Hi,

in your setup document, you are referring to " APPENDIX - DNSMasq setup" which seems to be gone.

Patrick

**Comment by woodnz** [comment]
Try here:

https://github.com/openshift/training/blob/master/deprecated/beta4/dnsmasq.conf

**Comment by thoraxe** [comment]
@PatrickSteiner The material has not been completely updated through 3.0.1. I am trying to reorganize into chapters since GA has been released and have not been able to keep up. PRs welcome.
