### ISSUE TITLE
Broken documentation link: 01-Requirements-and-Preparation.md#appendix---dnsmasq-setup

### ISSUE THREAD

**Issue by jwmatthews** [openshift/training#322]
The link to "appendix on dnsmasq" needs to be updated in:
https://github.com/openshift/training/blob/master/01-Requirements-and-Preparation.md#dns

 "It is possible to use dnsmasq inside of your beta environment to handle these duties. See the appendix on dnsmasq if you can't easily manipulate your existing DNS environment."

Broken link is:
  https://github.com/openshift/training/blob/master/01-Requirements-and-Preparation.md#appendix---dnsmasq-setup

Brenton pointed me to this which I'm using in the meantime:
https://github.com/openshift/training/blob/master/deprecated/beta-4-setup.md#appendix---dnsmasq-setup

**Comment by thoraxe** [comment]
I am doing a content re-org so most of the appendix links are going to be busted. I hope to get finished this week, but it's not looking good. Closing this for now - I know they're busted :)
