### ISSUE TITLE
Accessing https://hello-openshift.cloudapps.example.com didn't work for me

### ISSUE THREAD

**Issue by brenton** [openshift/training#34]
http work, https doesn't for some reason

```
[root@ose3-master ~]# curl -k -H "Host: hello-openshift.cloudapps.example.com" http://192.168.133.2
Hello OpenShift!
[root@ose3-master ~]# curl -k -H "Host: hello-openshift.cloudapps.example.com" https://192.168.133.2
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

```

**Comment by pweil-** [comment]
`curl -k --resolve hello-openshift-coudapps.example.com:443:<your router ip> https://hello-openshift-coudapps.example.com`

secure requires the SNI header to be sent, assuming your version of curl supports it (I think anything fairly recent will) that should work.  If not, we can check out the routes

**Comment by brenton** [comment]
Hmm, that still isn't working for me.  I'll dig deeper this morning:

```
# curl -k --resolve hello-openshift-coudapps.example.com:443:192.168.133.2 https://hello-openshift-coudapps.example.com
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
~~
```

**Comment by brenton** [comment]
Looking at routes.json in the router container I see:

```
    "ServiceAliasConfigs": {
      "hello-openshift.cloudapps.example.com-": {
        "Host": "hello-openshift.cloudapps.example.com",
        "Path": "",
        "TLSTermination": "",
        "Certificates": null
      }
    }
```

Is this simply due to the fact our `hello-openshift-route` is not requesting TLS explicitly at creation time?

**Comment by pweil-** [comment]
Yes, it looks like you only have a non-secure route defined.  Here is an edge terminated route that you can use if you don't want to generate certs: https://github.com/pweil-/hello-nginx-docker/blob/master/openshift/edge/route.json

**Comment by brenton** [comment]
Thanks Paul!

**Comment by thoraxe** [comment]
So, I don't have this issue with my browser when I don't include the TLS stuff. the sinatra example worked with https just fine.

**Comment by pweil-** [comment]
@thoraxe that is strange.  Steps to reproduce?  Also, did you previously have a TLS enabled route and then delete it?  Perhaps it is an issue cleaning up the certs.  If the cert was still laying around in the router and an https request came in it would be able to decrypt and pass it on (using the plain http backend assuming you have an unsecure route as well)

**Comment by sdodson** [comment]
I'm not able to reproduce this. Both https and http work fine for me.

**Comment by brenton** [comment]
The original was likely something else wrong in my environment that I didn't have time to debug.  I think the only remaining question is from @thoraxe's last comment.  I'll let him close this issue whenever he wants.

**Comment by thoraxe** [comment]
Couldn't reproduce.
