### ISSUE TITLE
Update NFS setup and configuration to take into account root_squash 

### ISSUE THREAD

**Issue by ivanthelad** [openshift/training#364]
The document https://github.com/openshift/training/blob/master/07-Registry-and-Storage.md#export-an-nfs-volume 
Outlines all_squash as a permission setting on the export. This causes problems with things such as postgres. The training should reflect the same instructions are outlined in the 3.1 documentation 
https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/persistent_storage_nfs.html

Addtionally it may be required to take into account the findings from the nfs setup resolved in this bugzilla 
https://bugzilla.redhat.com/show_bug.cgi?id=1282733#c48
- update Domain in /etc/idmapd.conf
- disable idmapping
  NFS client 
  echo 'Y' > /sys/module/nfs/parameters/nfs4_disable_idmapping
  NFS server
  echo 'Y' > /sys/module/nfsd/parameters/nfs4_disable_idmapping

**Comment by detiber** [comment]
@abutcher will need to make sure the nfs volume work takes this into account.  If we are going to muck with client settings, we may need to make it so that one can opt out of the nfs storage config in the node role.

**Comment by abutcher** [comment]
@detiber ack

**Comment by thoraxe** [comment]
@ivanthelad can you test/verify it works OK and then submit a PR?
