### ISSUE TITLE
Must switch to 'master' context before creating projects

### ISSUE THREAD

**Issue by brenton** [openshift/training#38]
When I ran this command I got a 403:

```
openshift ex new-project integrated --display-name="Frontend/Backend" \
--description='A demonstration of a "quickstart/template"' \
--admin=htpasswd:joe
```

At that point in the doc I was still in the sinatra context.  I'm guessing we have to switch back to the master context to run that.

**Comment by thoraxe** [comment]
yeah some pending changes will add logging in as different users and creating kubeconfigs and such. So this will go away shortly.

**Comment by thoraxe** [comment]
switched to root and non-root users in recent commits.
