### ISSUE TITLE
SSH Public Key is not always listed in interactive command

### ISSUE THREAD

**Issue by jiajliu** [openshift/training#385]
> $ ./openshift-install create cluster
> ? SSH Public Key /path/to/.ssh/id_rsa.pub

If there are *.pub in ~/.ssh/ directory, then all pub keys will be listed to show users to select one. But if there are not *.pub files in the directory, no SSH Public Key item will be provided in interactive command.

**Comment by thoraxe** [comment]
In the prerequisite steps we tell the user to create a key if they don't already have an available keypair to use. If they don't have any keypair then they won't be able to access any hosts via SSH after the install, which is bad.

I am open to suggestions here on what to suggest for output, but trying to account for all possible outcomes here might be difficult...

What do you think?

**Comment by jiajliu** [comment]
Yes. I noticed there were steps about ssh key in [1]. But according to my test, if the key is not named *.pub and not located in ~/.ssh/ directory, when it comes to interactive command, there is still not "SSH Public Key" item showed. 
My suggestion is that you can add key name and directory note  in [1]  if you want keep this "SSH Public Key" item here. Or else users maybe will not see this choice when run " ./openshift-install create cluster".
[1]https://github.com/openshift/training/blob/master/docs/01-prerequisites.md#ssh-keypair

**Comment by thoraxe** [comment]
@jiajliu what about (in SSH keypair section):

```
NOTE: if you do not have a pubkey with a `.pub` extension, the installer will not find it 
and you will not be able to select to use this SSH key with your instances, and you will 
not be able to SSH into them at all.
```

?

**Comment by jiajliu** [comment]
@thoraxe 
The previous part LGTM. But the last part about "you will not be able to SSH into them at all" seems so absolute. Users still can SSH after the cluster created. Please refer to https://github.com/openshift/installer/issues/862#issuecomment-446322340
