### ISSUE TITLE
Incorrect command shown in "Deleting the Cluster and Cleaning up"

### ISSUE THREAD

**Issue by gpei** [openshift/training#386]
In https://github.com/openshift/training/blob/master/docs/02-install.md#deleting-the-cluster-and-cleaning-up
`openshift-install destroy cluster`
Should be
`./openshift-install destroy cluster`

**Comment by thoraxe** [comment]
@gpei i had moved `openshift-install` into my path instead of leaving it in the local folder. good catch.
