### ISSUE TITLE
not every resource tagged with a key:value pair of clusterid:whatever_you_specified_during_install.

### ISSUE THREAD

**Issue by jianlinliu** [openshift/training#389]
In "Deleting the Cluster and Cleaning up" section:
'''
On the off chance that you experience a failure during the destroy operation, you will need to very carefully delete the resources that were created, by hand, from your AWS account. Fortunately they are all tagged with a key:value pair of clusterid:whatever_you_specified_during_install.
'''
That is not true, only instances are tagged with key:value pair of clusterid:whatever_you_specified_during_install, but LB, vpc do not have that tag. Most of resources created by installer are tagged with openshiftClusterID:cluster_uuid

**Comment by thoraxe** [comment]
@jianlinliu good to know, although that seems a bit of a bug in the installer, too.

Do you know how to find the cluster_uuid?

**Comment by gpei** [comment]
ClusterID in uuid format is a key filed in install-config.yaml, but after `destroy cluster` command, I think the only useful file may be `.openshift_install_state.json`

Here's how I find the clusterID in `.openshift_install_state.json`, I believe there should be a better way.

```
[root@gpei-preserve-ansible-slave new2]# grep '"clusterID"' .openshift_install_state.json
            "clusterID": "769fee2e-1521-4f3e-84f5-bfc15568d72c",
```

**Comment by jianlinliu** [comment]
User could run the following command in advance before destroy the cluster:
`oc get clusterversion -o jsonpath='{.spec.clusterID}{"\n"}' version`
But if user already run destroy cluster, have to get it from install log just as what gpei said.

**Comment by thoraxe** [comment]
I will update the docs with a suggested destroy procedure and you can review. Hang tight.

**Comment by thoraxe** [comment]
@jianlinliu will you please review the PR referenced (https://github.com/openshift/training/pull/395) and let me know if you are OK with it?

**Comment by jianlinliu** [comment]
LGTM.
