### ISSUE TITLE
wiring example cannot reuse the 'frontend' service

### ISSUE THREAD

**Issue by brenton** [openshift/training#39]
I followed the wiring example and when my route wasn't working I verified the pod was actually working as expected.  When looking at `routes.json` I noticed it was missing a section for the wiring backend.  It seems like the services are not namespaced in the router.  This means that we cannot reuse the name `frontend` that the integrated example already used.  This seems like a bug but we'll likely have to update the docs for now.

@rajatchopra, @abhgupta, either of you care to comment?

**Comment by pweil-** [comment]
Please see https://github.com/openshift/origin/pull/1213

**Comment by abhgupta** [comment]
@pweil- has already fixed this and it just got merged yesterday. The user does not need to specify the namespace for the service within the route. However, the router uses the route namespace to identify the service and also uses it to generate the namespace-aware key to store the route within its configuration.

**Comment by brenton** [comment]
I vote we simply rename the service in our examples (https://github.com/openshift/training/pull/42).  We'll have beta3 out soon enough and this will be fixed.

**Comment by abhgupta** [comment]
@brenton Is it too late to cherry-pick this commit for beta2?

**Comment by brenton** [comment]
It's not too late.  If it applies cleanly @sdodson can pull it in tomorrow.

**Comment by abhgupta** [comment]
@brenton while we should try to get this commit cherry-picked, I would definitely go ahead and merge the PR that renames the service in the example.

**Comment by sdodson** [comment]
It doesn't cherry-pick atop v0.4 cleanly without https://github.com/smarterclayton/origin/commit/4610229bb0c1e129aa824ea3037b7fdcccc403d6 which is part of the rebase. but it's trivial to resolve.

**Comment by pweil-** [comment]
Just FYI, I sent a note to QE to get a test case created for the PR that fixes the issue.  I also ran a manual test to verify the storage of same service name, different namespace for my own peace of mind (I previously tested the key storage was correct but didn't do a full test of this particular use case).  It looks fine: https://gist.github.com/pweil-/36e86754ce89f6726e31

**Comment by sdodson** [comment]
Fixed in openshift-0.4-0.git.45.42737cc.el7ose.x86_64 and more importantly the image openshift3_beta/ose-haproxy-router Image ID bf214560f013

**Comment by sdodson** [comment]
super simple test is to check /var/lib/containers/routes/routes.json then docker pull docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-docker-registry:v0.4 and kill the pod, when it restarts you should have namespaced routes.

**Comment by thoraxe** [comment]
reopen if this crops up again
