### ISSUE TITLE
[Doc] A clusterautoscaler is needed before auto scale up

### ISSUE THREAD

**Issue by jhou1** [openshift/training#391]
Doc: https://github.com/openshift/training/blob/master/docs/04-scaling-cluster.md

A ClusterAutoscaler should be created under the `openshift-cluster-api` namespace before kicking off the *Automatic Cluster Scale Up* section. If ClusterAutoscaler is absent, the cluster won't scale. 

A sample of ClusterAutoscaler:

```
apiVersion: "autoscaling.openshift.io/v1alpha1"
kind: "ClusterAutoscaler"
metadata:
  name: "default"
spec:
```

**Comment by thoraxe** [comment]
@jhou1 so you need to define the `ClusterAutoscaler` after you define https://github.com/openshift/training/blob/master/docs/04-scaling-cluster.md#define-a-machineautoscaler ?

**Comment by jhou1** [comment]
@thoraxe Actually I think we need to define `ClusterAutoscaler` before we define a `MachineAutoscaler`. The `MachineAutoscaler` annotates a `machineSet` to define its min/max node group sizes, the `ClusterAutoscaler` manages cluster scalings.

https://github.com/openshift/cluster-autoscaler-operator#custom-resource-definitions

**Comment by thoraxe** [comment]
FYI there's content in progress for this but it's not working against 4.0.0-9 / 0.90.1
