### ISSUE TITLE
[Doc] The version of Red Hat CoreOS is not correct.

### ISSUE THREAD

**Issue by qinpingli** [openshift/training#401]
Doc: https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#etcd-is-not-running

`etcd is started and managed by the Kubelet as a static pod. This requires a newer Kubelet which started shipping with version 47.29 of Red Hat CoreOS. `

The Red Hat CoreOS should be `47.249`, not `47.29`.

It should be a typo.

**Comment by thoraxe** [comment]
@qinpingli you have filed this issue in the training repo. Did you mean to file this issue in the installer repo?
