### ISSUE TITLE
[Doc] The Command of  getting SSH Key should use kubeconfig of the new install cluster. 

### ISSUE THREAD

**Issue by qinpingli** [openshift/training#402]
Doc: https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#unable-to-ssh-into-master-nodes

The command: `oc get configmap -o "jsonpath={.data['install-config']}" -n kube-system cluster-config-v1 | grep -A1 sshKey` should update to `oc --config=${INSTALL_DIR}/auth/kubeconfig  get configmap -o "jsonpath={.data['install-config']}" -n kube-system cluster-config-v1 | grep -A1 sshKey`

**Comment by thoraxe** [comment]
@qinpingli this is filed in the training repo and not the installer repo.
