### ISSUE TITLE
Document how an user needs to re-login to use oc command after initial install 

### ISSUE THREAD

**Issue by tkatarki** [openshift/training#403]
We need to document: 

When one opens a new terminal window and tries to access a previously installed OpenShift 4 cluster with oc, they can get errors documented in https://bugzilla.redhat.com/show_bug.cgi?id=1665935

To fix this: 
Have you run: 

> export KUBECONFIG=/PATH/TO/INSTALL/DIR/test_cluster/auth/kubeconfig
> oc login -u kubeadmin -p $(cat auth/kubeadmin-password)

If you run these two things you can re-gain kubeadmin on the cli

**Comment by tkatarki** [comment]
Sorry. Hold on. Looks like according to https://bugzilla.redhat.com/show_bug.cgi?id=1665842#c11 the above workaround is not actually working. Dev is looking at this. So please stand by.

**Comment by thoraxe** [comment]
"oc login" is not required after "export kubeconfig". The installer-generated kubeconfig already is a logged in user.

That being said, https://github.com/openshift/training/pull/405 tells someone to re-export.
