### ISSUE TITLE
Inconsistent PATH advice

### ISSUE THREAD

**Issue by wking** [openshift/training#416]
The current docs suggest that [`oc` be installed in the `PATH`][1], but [don't bother putting the installer in the `PATH`][2].  I'd have expected to go the same way for both (and I have both in my `PATH`).  But you could also argue that `oc` is forever, while the installer is use-and-discard, and therefore not worth the trouble of a `PATH` install.  The `PATH` references are from 88bba2d9 (#383), where I don't see them discussed, so I thought I'd mention my surprise in case folks wanted to revisit the approach.  I'm also fine if folks want to stick with the current approach.  CC @thoraxe, who wrote 88bba2d9.

[1]: https://github.com/openshift/training/blame/185e9e6c1190e9b3ebf4a5028d3128b732c1618c/docs/01-prerequisites.md#L140
[2]: https://github.com/openshift/training/blame/185e9e6c1190e9b3ebf4a5028d3128b732c1618c/docs/02-install.md#L25

**Comment by thoraxe** [comment]
I was just copy-pasting from the original Google doc. I don't particularly care either way -- path or no path is fine with me.

I personally put it in my path. Takes 2 seconds. If you want to work up a PR for that, I'm cool with it.
