### ISSUE TITLE
AWS CLI is not a must on provisioning host but documenation said it is

### ISSUE THREAD

**Issue by liangxia** [openshift/training#418]
Document URL: 
Section Number and Name: 
https://github.com/openshift/training/blob/master/docs/01-prerequisites.md#aws-cli

Describe the issue: 
The doc said AWS CLI is a must on the provisioning host, but it is not a must.

Suggestions for improvement: 
Changes the sentences accordingly as it isn't a must, but a better to have.
Actually, access key ID and secret can be provides interactively via openshift-install

**Comment by thoraxe** [comment]
https://cloud.openshift.com/clusters/install points you to https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html#cli-environment which is CLI instructions.

You are correct, you can get a key and ID via other means.

Feel free to submit a PR but it's good enough for drop 1.
