### ISSUE TITLE
What is the requirement for `Base Domain`?

### ISSUE THREAD

**Issue by hongkailiu** [openshift/training#421]
```
? Base Domain openshift4-beta-abcorp.com
```

So far I have seen 2: Both of them are auto-completed by the installer.

* `devcluster.openshift.com`
* `qe.devcluster.openshift.com`

I might have missed it if documented already.
If not, maybe include it [prerequisites.md](https://github.com/openshift/training/blob/master/docs/01-prerequisites.md).

**Comment by thoraxe** [comment]
https://github.com/openshift/training/blob/master/docs/01-prerequisites.md#additional-aws-requirements

^^ describes the DNS/domain requirements. Is there something here you don't find clear?

Your Route53 account has those 2 domains in it. What were you expecting to see?

**Comment by hongkailiu** [comment]
@thoraxe 
Thanks.
Totally my fault.
