### ISSUE TITLE
Update to .spec.providerConfig to .spec.providerSpec

### ISSUE THREAD

**Issue by SSshahan** [openshift/training#422]
It seems that the `.spec.providerConfig` section of a Machine resource change to  `spec.providerSpec` in the latest payload. In the section `Amazon Web Services` of `Managing Compute` still use the `.spec.providerConfig` and cannot get instance type using the original command, so it should update to `oc get machines -n openshift-cluster-api -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{"\t"}{.spec.providerSpec.value.instanceType}{end}{"\n"}'`. BTW, please notice the **text** where  still use the `spec.providerConfig`, there also need to update.

**Comment by thoraxe** [comment]
@SSshahan are you talking about https://github.com/openshift/training/blob/master/docs/compute/01-managing-compute.md ?

Any pages that aren't directly linked from the README have not been tested and are somewhat out of scope. Feel free to submit a PR with any necessary changes.

**Comment by SSshahan** [comment]
The specific link:  https://github.com/openshift/training/blob/master/docs/compute/01-managing-compute.md#amazon-web-services

**Comment by thoraxe** [comment]
Those docs were just nuked.
