### ISSUE TITLE
Copy the .kubeconfig file into a place where the CLI tools look for 

### ISSUE THREAD

**Issue by anpingli** [openshift/training#43]
Should we copy /var/lib/openshift/openshift.local.certificatesopenshift-client/.kubeconfig instead of 
/var/lib/openshift/openshift.local.certificates/admin/.kubeconfig  ?

**Comment by thoraxe** [comment]
I am pretty sure no. I'm also generating a .kubeconfig via `ex login` for non-priv'd users now.
