### ISSUE TITLE
need firstly terminate ssh bastion before destroy cluster

### ISSUE THREAD

**Issue by jianlinliu** [openshift/training#444]
In https://github.com/openshift/training/blob/master/docs/03-explore.md#exploring-rhel-coreos, there is some doc mentioned:
'''
It does not matter what OS you choose for this instance, as it will simply serve as an SSH bastion to bridge the internet into your OCP VPC.
'''
Once this bastion is created, you have to terminate (not stop) this bastion to release VPC network, or else, this would block your cluster destroy operation because of vpc dependency.

**Comment by thoraxe** [comment]
Covered in https://github.com/openshift/training/blob/master/docs/98-cleanup.md
