### ISSUE TITLE
Discuss project/namespace early on.

### ISSUE THREAD

**Issue by sosiouxme** [openshift/training#5]
It seems to me that training should discuss projects much earlier. IMHO, everything being deployed that's not infrastructure (router, registry) ought to be in a project (not "default").

This experience sucks a bit, as you have a choice of adding "-n foo" everywhere or "openshift ex config" / edit .kubeconfig / manually create ~/.kubecfg_ns. But it just seems like good hygiene.

**Comment by thoraxe** [comment]
A few issues:

1) -n foo doesn't actually seem to work in a lot of places. I find that "osc create -n foo -f blah" will barf but "osc create --namespace=foo -f blah" will not. I'm not sure when the -n syntax is valid or not, but it seems picky.

2) That's not a bad idea (projects). I wonder if I should introduce the web console earlier?

3) There's a bug with the root user and osc -- you can't "set" a namespace.

**Comment by sosiouxme** [comment]
1 sounds like a bug... should work either way

3 is not a bug so much as a change in direction. "osc namespace" is going away. So for now you're stuck with the choices I mentioned for choosing a namespace.

Not a bad idea to introduce the web console earlier, but OTOH it's not particularly necessary either...

**Comment by thoraxe** [comment]
On Monday I'll investigate #1.

Understood on #3 but that is actually quite annoying. Is there a way to export an env var to set your project/namespace?

If we move projects earlier it makes sense to move web console earlier, IMO.

**Comment by sosiouxme** [comment]
Re 1 what you noticed might have been this:

```
osc create -n foo -f test-complete.json
osc create -n=foo -f test-complete.json
osc create --namespace=foo -f test-complete.json
```

These are all identical. But without the "=" sign:

```
# osc create --namespace foo -f test-complete.json                                                                                                                          
flag needs an argument: --namespace

Options:
  -f, --filename=[]: Filename, directory, or URL to file to use to create the resource

Use "osc options" for a list of global command-line options.
```

Weird go-cobra-ism I guess.

**Comment by thoraxe** [comment]
Moved namespaces/projects and web console much earlier.
