### ISSUE TITLE
may need to mention that libselinux-python needs to be installed

### ISSUE THREAD

**Issue by chmouel** [openshift/training#56]
Thanks for this training documentation, very well written

The only gotcha so far is running under selinux while launching the ansible playbook will fail with :

 failed: [ose3-node1.example.com] => {"failed": true}
 msg: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!

installing the package fixes the issue,

not sure if this should be fixed in the openshift-ansible repo or here

**Comment by detiber** [comment]
@chmouel @thoraxe It looks like libselinux-python is only used by a subset of the ansible modules. I can go ahead and update the roles such that we are making sure it is installed before it is needed.

**Comment by detiber** [comment]
@thoraxe The PR referenced above is for the upstream changes. I've added these changes to the v3-beta2, v3-beta3 and enterprise2 branches already.

**Comment by chmouel** [comment]
Thanks!
