### ISSUE TITLE
[beta2] Would be helpful to give a brief overview of the topology being used

### ISSUE THREAD

**Issue by sspeiche** [openshift/training#60]
I had a hard time piecing together what I was accomplishing in the beta 2 setup in the sense that there were some assumptions about the configuration (ose3-master, ose3-node1, ose3-node2, a couple of users, apps, etc).  I would be helpful to have some brief overview in text and/or diagram to help illustrate this.

See https://github.com/openshift/training/blob/master/beta-2-setup.md

**Comment by thoraxe** [comment]
If you put together a drawing I'd be happy to write something up for the beta3 branch.

**Comment by thoraxe** [comment]
https://github.com/openshift/training/commit/2932ed3cb7b6fd7019a3dd6d4861a38259fdfdb2

This adds a little more color on the topology. Let me know what else could be added/improved.
