### ISSUE TITLE
[beta2] Subscription Manager setup in setup instructions

### ISSUE THREAD

**Issue by sspeiche** [openshift/training#61]
There seems to be some assumption about why an end user can do with RH subscriptions.  It would be helpful to set that as a prereq or a point to some help in section [Preparing Each VM](https://github.com/openshift/training/blob/master/beta-2-setup.md#preparing-each-vm) which first hits on this.

Typical errors one might see if not a properly signed on subscriber would be:
- \* is not a valid repository ID
- "rhel-server-7-ose-beta-rpms" is not a valid repository ID
- later in "Run the Ansible Installer"

```
    TASK: [openshift_master | Install OpenShift Master package] ******************* 
    failed: [ose3-master.example.com] => {"changed": false, "failed": true, "rc": 0, "results": []}
    msg: No Package matching 'openshift-master' found available, installed or updated

    FATAL: all hosts have already failed -- aborting

    PLAY RECAP ******************************************************************** 
               to retry, use: --limit @/root/config.retry

    ose3-master.example.com    : ok=23   changed=6    unreachable=0    failed=1  
```

**Comment by thoraxe** [comment]
I don't understand what the issue is here. If you got an error trying to set up the subscriptions, you shouldn't have continued.

If you got an error about "not a valid repository", it's because you don't have the right subscriptions attached.

Are you just asking for more instructions on how to use subscription manager?

**Comment by thoraxe** [comment]
I added a little more color on subscription manager in https://github.com/openshift/training/commit/2932ed3cb7b6fd7019a3dd6d4861a38259fdfdb2 

Short of providing a link to access.redhat.com's knowledgebase on subscription manager, I'm not sure what else could be useful.
