### ISSUE TITLE
[beta2] Setup instructions a bit mysterious what on what ansible playbook is doing

### ISSUE THREAD

**Issue by sspeiche** [openshift/training#62]
Without knowing too much ansible, I found it a bit mysterious what `ansible-playbook playbooks/byo/config.yml' was really doing.  The section titled [Run the Ansible Installer](https://github.com/openshift/training/blob/master/beta-2-setup.md#run-the-ansible-installer) and subsequent ones, I wasn't sure what state it would be after the installer.  A few words on what it was doing (perhaps the answer will be read config.yml)

**Comment by thoraxe** [comment]
I mean... it's installing the things. Since the master is a master and a node, it's installing and configuring master and node.

Maybe I'm assuming too much... but other than saying just that ("it's installing and configuring the software") what am I missing?

**Comment by thoraxe** [comment]
Let me know if https://github.com/openshift/training/commit/2932ed3cb7b6fd7019a3dd6d4861a38259fdfdb2 makes things a little clearer. I am totally not trying to sound snarky!

**Comment by sspeiche** [comment]
I think it is a good improvement (and I didn't hear any snarky-ness)

Thanks,
Steve Speicher
http://stevespeicher.me
