### ISSUE TITLE
[beta2] Setup for adding customer STI scripts not as expected

### ISSUE THREAD

**Issue by sspeiche** [openshift/training#65]
In going through [Add a Script](https://github.com/openshift/training/blob/master/beta-2-setup.md#add-a-script) I must confess to never having used GitHub web interface to do this.  I could do this simply from CLI and would expect most users to.  Perhaps a minor point but found this a bit unusual from typical flow.

**Comment by thoraxe** [comment]
Not everyone that is doing the beta training is a developer. For those that know how to just do it themselves with command-line tooling, nothing prevents them from doing so. But, there are a lot of admins and other folks who are playing with this, so I tried to make it as "easy" as possible.
