### ISSUE TITLE
[beta2] Wordpress Docker image setup instructions state wrong subfolder

### ISSUE THREAD

**Issue by sspeiche** [openshift/training#66]
Looking at [Arbitrary Docker Image (Builder)](https://github.com/openshift/training/blob/master/beta-2-setup.md#arbitrary-docker-image-builder), the subfolder `beta2/wordpress` is empty...so I grabbed from CentOS location

**Comment by thoraxe** [comment]
I originally planned on doing it this way. The command works as described because it points to the repo directly.

**Comment by thoraxe** [comment]
Fixed by https://github.com/openshift/training/pull/68
