### ISSUE TITLE
openshift-sdn-node doesn't start openshift-node

### ISSUE THREAD

**Issue by sosiouxme** [openshift/training#7]
"Do not start the openshift-node service yet. We must start the openshift-sdn-node first in order to set up the proper bridges, and the openshift-sdn-node service will automatically start the openshift-node service for us."

At this time it doesn't.

**Comment by thoraxe** [comment]
@sosiouxme as best I can tell for the last week or so openshift-sdn-node currently starts openshift-node when started.

**Comment by sosiouxme** [comment]
That's weird because it has literally never worked for me, and doesn't now with the latest puddle. Of course I'm just updating the same systems repeatedly, perhaps there's something broken on my systems that I'm perpetuating that way.

**Comment by thoraxe** [comment]
Worked for me this morning so... yeah?

Maybe your node service file isn't getting updated?
