### ISSUE TITLE
namespaces shouldn't have hyphens

### ISSUE THREAD

**Issue by sosiouxme** [openshift/training#8]
(Note for anyone following the beta1 script as I know Erik filed https://github.com/openshift/origin/issues/933)

Although openshift/kubernetes currently allow your namespace to have dashes and periods, when this namespace is used in an image you're building, the registry won't accept it. You'll get something like:

```
Successfully built 172.30.17.217:5001/integrated-project/origin-ruby-sample
Build error: API error (500): Invalid namespace name (integrated-project), only [a-z0-9_] are allowed, size between 4 and 30
```

This is arguably a bug in OS/k8s... namespace validations should probably match the registry. But for now, use  namespaces that will be valid with the registry if you're going to build an image.

**Comment by thoraxe** [comment]
I'll update this shortly to remove hyphens.

**Comment by sosiouxme** [comment]
Also I believe what's actually going to happen (eventually) is that the docker-registry will (v2) accept hyphens in the namespace. But not for now.

**Comment by thoraxe** [comment]
Removed hyphens.
